### ISSUE TITLE
Missing courses without a course level

### ISSUE THREAD

**Issue by ColeFrench** [ekzhang/classes.wtf#10]
We incorrectly assume that every course has a `Course Level`, when in fact some don't. This is confirmed by exhausting all course levels—`(Course Level:"UGRDGRAD" | Course Level:"GRADCOURSE" | Course Level:"INTRO" | Course Level:"NOLEVEL" | Course Level:"PRIMGRAD" | Course Level:"PRIMUGRD")`—and then doing a wildcard search within FAS. The difference is about 50 courses.

The fix **specific to our use case of excluding graduate-level courses** is to query all courses that do not match `(Course Level:"GRADCOURSE")`. This can be done efficiently for my.harvard by setting the `Exclude300` flag and in GraphQL by using a filter.

**Comment by ekzhang** [comment]
I'm not sure this is necessary unless those 50 courses are especially important. The reason why we exclude 300-level courses is because they're edge cases that aren't relevant to students looking for classes; it sounds like these uncategorized courses are also edge cases.
