### ISSUE TITLE
my.harvard queries with multiple ORs do not work as expected

### ISSUE THREAD

**Issue by ColeFrench** [ekzhang/classes.wtf#11]
Queries of the form, `("A":"1" | "B":"2") ("C":"3" | "D":"4")`, do not yield the same results as the union of the queries, `("A":"1") ("C":"3" | "D":"4")` and `("B":"2") ("C":"3" | "D":"4")`. I'm hoping this issue can lay out systematically how they differ.

**Comment by ekzhang** [comment]
What do you mean?

**Comment by ColeFrench** [comment]
Here's a concrete example to organize my thoughts. Consider these queries:
| **Query** | **# Results** |
|-|-|
| $`q_1=\text{(Term:``2238'' \| Term:``2242'')}`$ | 12828 |
| $`q_2=\text{(Course Level:``PRIMUGRD'' \| Course Level:``UGRDGRAD'')}`$  | 2759 |
| $`q_3=q_1\ q_2`$ | 12828 |

Note that a `|` between fields is a logical "or" and a ` ` is a logical "and". To find all courses that satisfy $`q_1`$ and $`q_2`$, we expect that we can chain them together as in $`q_3`$. As a sanity check, we should receive at most 2759 results, but to our surprise, we get the same courses as $`q_1`$ alone.

The exact same behavior is observed no matter the order of the conjuncts and no matter which course levels are selected, as long as there are at least two.

**Comment by ColeFrench** [comment]
It seems like the second conjunct is just being ignored, but we can't say that about all queries like this. (Second example to follow.)

**Comment by ekzhang** [comment]
If it's easier then I think `-Exclude300` is probably fine.

If it helps to get a diff of the courses that are in one query but not another, you can `brew install duckdb` and run in the `duckdb` cli:

```sql
WITH
	new AS (SELECT * FROM 'data/courses-XXX.json'),
	old AS (SELECT * FROM 'data/courses-YYY.json')
SELECT
	id, subject || ' ' || catalogNumber AS courseNumber, semester, title
FROM
	new
WHERE
	id NOT IN (SELECT id FROM old);
```

**Comment by ColeFrench** [comment]
> If it's easier then I think `-Exclude300` is probably fine.

Thanks, I'm going to make a PR soon that uses this, which will resolve this and #10. Since I have time, I still intend to figure out what's going on here, even though we'll no longer be concerned with the issue.

> If it helps to get a diff of the courses that are in one query but not another, you can `brew install duckdb` and run in the `duckdb` cli:

Very useful thank you 😁.
