### ISSUE TITLE
AY 22-23 course meeting times in noon hour displayed incorrectly

### ISSUE THREAD

**Issue by aceriverson** [ekzhang/classes.wtf#3]
For example, FRSEMR 60r which meets from 12:00-2:45pm is displayed as 24:00-14:45.

Courses which meet off the hour also have this issue. For example, PORTUG 220.

I am unsure if courses which end in the noon hour also have the end time affected.

Some course entries on my.harvard are incorrect such as ECON 2909 which meets from 10:30-11:45am but is listed as 10:30am-11:45pm. As such, it is correctly displayed as 10:30-23:45.

This bug only applies to courses in AY 2022-2023.

**Comment by ekzhang** [comment]
🤦‍♂️ Oops! Good catch. You described the bug perfectly. I'll fix it in a sec.
