### ISSUE TITLE
Local my.harvard course list has duplicates

### ISSUE THREAD

**Issue by ColeFrench** [ekzhang/classes.wtf#7]
We send concurrent requests to my.harvard and aggregate the results, removing duplicates. (The key to uniquely identify courses is aptly named, `Key`.)

However, I don't believe we should be seeing duplicates; when I manually search for allegedly duplicate courses, only one result shows up. Also, each time the course download script is run, a different number of duplicates are removed.

**Comment by ColeFrench** [comment]
~~I'll see if the solution to #8 fixes this and work from there.~~

**Comment by ColeFrench** [comment]
Ok, so it looks like it's intended behavior to not match the `HitCount` locally, because we expect to receive duplicate results and remove them. But does my.harvard actually produce duplicates, or are we seeing them because of a bug in our code? I updated the issue to reflect this question.

**Comment by ColeFrench** [comment]
The problem is simply that the order of results is inconsistent across searches. Since we request each page separately, a course may show up on no pages, one page, or multiple pages.

We can fix this by requesting the results to be ordered by a unique key. AFAIK, course IDs are unique, so we can add `SortOrder: ["CRSE_ID"]` to our queries.

A nitpick of this solution is that each course already has a `Key` that is composed of other properties in addition to the course ID, but the API is unable to sort by `Key`. Perhaps a more robust solution is to figure out how my.harvard tracks the user's session to fix the order of results in the UI; if we can send each request from the same session, then we don't have to rely on a sort order.

**Comment by ekzhang** [comment]
> The problem is simply that the order of results is inconsistent across searches. Since we request each page separately, a course may show up on no pages, one page, or multiple pages.

Oh geez, that sounds like a bug on the My.Harvard side then. Does it only happen for searches that return a lot of courses?

**Comment by ekzhang** [comment]
> Perhaps a more robust solution is to figure out how my.harvard tracks the user's session to fix the order of results in the UI; if we can send each request from the same session, then we don't have to rely on a sort order.

Ah, I had no idea there was a session at all. So this means that if you make the same query to My.Harvard twice, in two separate sessions, it's possible to get different result orders?

**Comment by ColeFrench** [comment]
It's proven very difficult to pinpoint the cause of this issue 😩. What I've done so far leads me to believe it comes down to buggy pagination on the server side.

# Browser testing
> So this means that if you make the same query to My.Harvard twice, in two separate sessions, it's possible to get different result orders?

Yes, but now it seems there is no session tracking. My manual testing workflow in the browser has been:
1. Open the Network panel of the developer tools.
2. Submit a search on my.harvard.
3. Copy the request as a `fetch()`.
4. Disable caching (either with the checkbox in the Network panel or by setting the appropriate headers).
5. [Include or omit credentials.](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included) I don't notice any difference between the two, which is why I say there's no session tracking.
6. Modify the payload as you wish to change the sorting method or page number. Not specifying a sorting method will still result in the default sort by "relevance."
7. Send the request.

The page returned to me is one of two possibilities; call them `A` or `B`. I can't figure out what causes me to get one or the other, but one set, say `A`, is much more common. I will replay requests and receive a lot of `A`s, after which I receive a `B` or two before reverting back to `A`s.

At one point, I was able to induce a `B` from a page by requesting some other page and then requesting the original page. That latter request always gave me a `B`, after which replays returned `A`s. I can no longer reproduce this.

Nonetheless, we can conclude that **it is possible to receive different results from identical page requests.** This enables the observed behavior that courses are duplicated or do not appear in the accumulated results across all pages.

# Code testing
Let me just say, it was so much more pleasant to do automated tests with the code 😌. My findings amplify and elaborate on the manual browser testing.

First, I debugged the existing behavior that finds hundreds of duplicates with the default sorting method. There are courses that appear on two pages, three pages, and possibly more. Furthermore, since the total number of results including duplicates is the same as the total number we expect without duplicates, we know that some courses are not present at all.

We haven't touched the sorting method yet, so let's sort by course title. This can still produce tens of duplicates; consider this: There are 75 courses with a title of `Tutorial - Senior Year`! It doesn't help at all to sort these by course title with no way to arbitrate further.

The observed behavior is that sometimes courses with the same title are duplicated across consecutive pages. One way to explain this is that when the server is determining which results to show on the current page, it remembers which title it left off at on the previous page and starts from the next title, which may be the same. The server doesn't keep track of which courses went to the previous page, and its arbitrary pick of courses with the same title ends up being a duplicate.

That explanation is probably inaccurate, but it helps to conceptualize 🤷. Anyway, as far as we're concerned, the explanation isn't too important, because **we can resolve the issue if we sort such that there is no arbitration.**

# Resolution
We would love to sort by `Key`, but some fields including it are unable to be used. Generally, uppercase fields are allowed. I propose we sort by `CRSE_ID` or `URL_URLNAME`. Despite many runs, I haven't been able to produce duplicates with either.

`CRSE_ID` is a little scary, because there can be many results with the same one. A course ID uniquely identifies a "course" in the common sense; CS50 is a course, for example. But courses can be offered in multiple semesters and have multiple sections, all of which appear on my.harvard under the same course ID.

It seems like a better option is to use `URL_URLNAME`, which encodes all the fields that logically identify a search result. Here is CS50's for its only published section this fall: https://locator.tlt.harvard.edu/course/colgsas-152514/2023/fall/14862. Yeah, it's the locator link. I verified that each course this academic year has one, and it uniquely identifies the course.

Long post, but any thoughts?

**Comment by ekzhang** [comment]
Thanks for the really thorough investigation! Let's see:

> The page returned to me is one of two possibilities; call them `A` or `B`. I can't figure out what causes me to get one or the other, but one set, say `A`, is much more common. I will replay requests and receive a lot of `A`s, after which I receive a `B` or two before reverting back to `A`s.
> 
> At one point, I was able to induce a `B` from a page by requesting some other page and then requesting the original page. That latter request always gave me a `B`, after which replays returned `A`s. I can no longer reproduce this.
> 
> Nonetheless, we can conclude that **it is possible to receive different results from identical page requests.** This enables the observed behavior that courses are duplicated or do not appear in the accumulated results across all pages.

The most important thing is what you've observed and how you want to fix it. But to offer a possible theory: 

Since you're not seeing sessions be a part of it, one possible explanation is that My.Harvard, somewhere in their infrastructure, is simply running two replicas of their search engine, say A and B. These would have their own individual indices ordered non-deterministically at startup time, and then your request would go to one of the search engines with load balancing.

The search endpoint uses HTTP/2, so multiple HTTP requests are multiplexed on a single TCP connection that your browser makes to the server (this is true for HTTP/1.1 and higher). It's possible that this could cause the non-deterministic behavior  because the load balancer could statefully route all your requests to server A, but then later on when the browser makes a second TCP connection (closing and opening pages, waiting a while, etc.), it gets routed to server B.

> We would love to sort by `Key`, but some fields including it are unable to be used. Generally, uppercase fields are allowed. I propose we sort by `CRSE_ID` or `URL_URLNAME`. Despite many runs, I haven't been able to produce duplicates with either.
> 
> `CRSE_ID` is a little scary, because there can be many results with the same one. A course ID uniquely identifies a "course" in the common sense; CS50 is a course, for example. But courses can be offered in multiple semesters and have multiple sections, all of which appear on my.harvard under the same course ID.
> 
> It seems like a better option is to use `URL_URLNAME`, which encodes all the fields that logically identify a search result. Here is CS50's for its only published section this fall: https://locator.tlt.harvard.edu/course/colgsas-152514/2023/fall/14862. Yeah, it's the locator link. I verified that each course this academic year has one, and it uniquely identifies the course.

Either option sounds great to me!

**Comment by ColeFrench** [comment]
Thanks for the insight! I hadn't considered load balancing, and what you say makes a lot of sense.

However, [I used `httptrace` to inspect our TCP connections](https://golang.cafe/blog/how-to-reuse-http-connections-in-go.html) and conclude that we are reusing the same connection for every request. Perhaps my.harvard is [load balancing HTTP requests on the same TCP connection](https://serverfault.com/questions/1121009/can-load-balancers-do-balancing-of-multiple-requests-received-on-the-same-tcp-co).

I'll go ahead and make the PR to close this!

**Comment by ekzhang** [comment]
Great, makes sense! That sounds possible
