### ISSUE TITLE
Queries restricted to specific terms return more courses from my.harvard than expected

### ISSUE THREAD

**Issue by ColeFrench** [ekzhang/classes.wtf#8]
In order to get all courses offered in an academic year, we query the fall and spring term. However, we currently encode the term specification using the incorrect key, `Term`, instead of `STRM`.

Our mistake is using the "localized" name rather than the "unlocalized" one. For example, each course has a `Course Level` that indicates for which group of students a course is intended, and this localized name is displayed in my.harvard's search input for readability. However, the key actually sent in the HTTP request is the unlocalized name, `CRSE_ATTR_VALUE_HU_LEVL_ATTR`.

my.harvard's frontend supports either version of the key, transparently translating from localized to unlocalized. We do not do this, and **the REST API only supports unlocalized keys;** unrecognized search components are silently ignored. For example, the query, `anime (Course Level:"PRIMUGRD") (STRM:"2238" | Term:"2242")`, is the same as just `anime (STRM:"2238")`.

**Comment by ekzhang** [comment]
Thanks Cole! Would you be able to rerun the script with the new version of the tag?

**Comment by ColeFrench** [comment]
I'll try! 😂 Just need to fix the `Course` struct to account for what we've learned from all the new courses that show up, and then hopefully there's no issue.

**Comment by ekzhang** [comment]
Oh sweet! :D Thanks so much for that, every problem that's fixed makes it more robust in the future
