### ISSUE TITLE
Cannot page beyond 10,000th course on my.harvard

### ISSUE THREAD

**Issue by ColeFrench** [ekzhang/classes.wtf#9]
my.harvard appears to use [Oracle WebLogic Server](https://en.wikipedia.org/wiki/Oracle_WebLogic_Server), which in turn uses [Elasticsearch](https://en.wikipedia.org/wiki/Elasticsearch) to service course search queries. Elasticsearch's pagination API allows paging to the 10,000th course at most.[^1]

When we reach this limit, my.harvard returns an error message (albeit with a 200 code) instead of a JSON object.

[^1]: https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html

**Comment by ColeFrench** [comment]
We can solve this by partitioning courses using narrower queries (e.g., search for each term separately rather than together). There shouldn't be more than 10,000 courses per semester, and if there are, we'll just print the error.

**Comment by ColeFrench** [comment]
Improved error handling in https://github.com/ekzhang/classes.wtf/commit/b53740e59eb75f0948e5f87a0cf625e928783254, so we can actually see what the error message is!

**Comment by ekzhang** [comment]
Good to know, yes let's implement a cursor instead of paging with something like [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after), or split up the query by year.
